language: node_js
node_js:
- lts/*

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
    - if: tag IS present
      stage: deploy to production
      script: npm run build
      deploy:
        provider: heroku
        api_key:
          secure: "$HEROKU_KEY"
        app: love-for-banners
        skip_cleanup: true
        on:
          repo: dracomithril/love-for-banners