language: node_js
node_js:
- lts/*

script:
- npm run lint
- npm run build

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: love-for-banners
  on:
    repo: dracomithril/love-for-banners