language: node_js
node_js:
- lts/*

jobs:
  include:
    - stage: test
      script:
          - yarn run lint
          - yarn run test
    - if: tah IS present
      stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: "$HEROKU_KEY"
        app: love-for-banners
        skip_cleanup: true
        on:
          repo: dracomithril/love-for-banners